version: "3.9"

services:
  web:
    build: .
    container_name: biomed
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: biomed
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/custom.cnf
      - biomed_db:/var/lib/mysql
volumes:
  biomed_db:
