FROM python:3.9-slim-buster

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /biomed

# Install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /biomed/
RUN pip install -r requirements.txt

# Copy project
COPY . /biomed/

EXPOSE 8000

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
CMD python manage.py runserver 0.0.0.0:8000