version: "3.9"

services:
  web:
    build: .
    container_name: biomed
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    volumes:
      - biomed_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=biomed
      - POSTGRES_PASSWORD=biomed
      - POSTGRES_DB=biomed
volumes:
  biomed_data:
