# Generated by Django 3.0.6 on 2020-05-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.IntegerField(default='000', primary_key=True, serialize=False, unique=True),
        ),
    ]
