# Generated by Django 3.0.6 on 2020-05-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20200524_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
