# Generated by Django 3.0.6 on 2020-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20200524_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
